### ISSUE TITLE
2-section of H details

### ISSUE THREAD

**Issue by spagnuolocarmine** [pszufe/SimpleHypergraphs.jl#4]
According to the 2-section of H definition in: 
Alain Bretto. 2013. Hypergraph Theory: An Introduction. Springer Publishing Company, Incorporated.

We produce a 2-section of H in similar fashion of BipartiteView.

Suggestions?

**Comment by pszufe** [comment]
@spagnuolocarmine this is all OK. If it makes sense for youm you or @aleant93 can put some code snippets here for the discussion (like I did at the another issue).

**Comment by spagnuolocarmine** [comment]
Ok! We have developed the 2section view, we can do a pull request  (@aleant93) and we discuss on it.

**Comment by pszufe** [comment]
Great! create the PR for discussion.
